packages:
  - frontend
  - backend
  - shared
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@scarf/scarf'
  - esbuild
allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': true
  esbuild: true
